#!/bin/sh

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 script_name" >&2
  exit 1
fi

script_name=$1

echo "#!/usr/local/bin/scalas

/***
scalaVersion := \"2.11.7\"
libraryDependencies ++= Seq()
*/

!#

" > $script_name
chmod +ux $script_name
